@ECHO OFF

setlocal
SET ICCDIR=f:\lang\ibmcpp

SET ENDLIBPATH=f:\lang\os2tk45\samples\mm\dll;f:\lang\os2tk45\som\common\dll;f:\lang\os2tk45\som\lib;f:\lang\os2tk45\dll;%ICCDIR%\DLL;%ENDLIBPATH%;
SET PATH=f:\lang\os2tk45\som\common;f:\lang\os2tk45\som\bin;f:\lang\os2tk45\bin;%ICCDIR%\BIN;%ICCDIR%\SMARTS\SCRIPTS;%ICCDIR%\HELP;%PATH%
SET DPATH=f:\lang\os2tk45\som\common\system;f:\lang\os2tk45\som\msg;f:\lang\os2tk45\msg;g:\books;%ICCDIR%\HELP;%ICCDIR%;%ICCDIR%\LOCALE;%ICCDIR%\MACROS;%ICCDIR%\BND;%DPATH%
SET HELP=%ICCDIR%\HELP;%ICCDIR%\SAMPLES\TOOLKIT\HELP;%HELP%
SET BOOKSHELF=%ICCDIR%\HELP;%BOOKSHELF%
REM SET SOMIR=%SOMIR%;%ICCDIR%\ETC\SOM.IR;
SET CPPHELP_INI=E:\OS2\SYSTEM
SET LOCPATH=%LOCPATH%;%ICCDIR%\LOCALE;
SET INCLUDE=f:\lang\os2tk45\speech\h;f:\lang\os2tk45\som\include;f:\lang\os2tk45\inc;f:\lang\os2tk45\h\gl;f:\lang\os2tk45\h;%ICCDIR%\INCLUDE;%ICCDIR%\INCLUDE\OS2;%ICCDIR%\INC;%ICCDIR%\INCLUDE\SOM;%INCLUDE%
SET SMINCLUDE=f:\lang\os2tk45\h;f:\lang\os2tk45\idl;f:\lang\os2tk45\som\include;.;%ICCDIR%\INCLUDE\OS2;%ICCDIR%\INCLUDE;%ICCDIR%\INCLUDE\SOM;%SMINCLUDE%
REM DEVICE=%ICCDIR%\SYS\CPPOPA3.SYS
SET VBPATH=.;%VBPATH%;%ICCDIR%\DDE4VB;
SET TMPDIR=%TEMP%
SET LXEVFREF=EVFELREF.INF+LPXCREF.INF
SET LXEVFHDI=EVFELHDI.INF+LPEXHDI.INF
SET LPATH=%ICCDIR%\MACROS;%LPATH%
SET CODELPATH=%ICCDIR%\CODE\MACROS;%ICCDIR%\MACROS;%LPATH%
SET CLREF=CPPCLRF.INF+CPPDAT.INF+CPPAPP.INF+CPPWIN.INF+CPPCTL.INF+CPPADV.INF+CPP2DG.INF+CPPDDE.INF+CPPDM.INF+CPPMM.INF+CPPCLRB.INF
SET IPFC=%ICCDIR%\IPFC
SET LIB=f:\lang\os2tk45\speech\lib;f:\lang\os2tk45\samples\mm\lib;f:\lang\os2tk45\lib;f:\lang\os2tk45\som\lib;%ICCDIR%\LIB;%ICCDIR%\DLL;%LIB%
SET SOMRUNTIME=%ICCDIR%\DLL
SET CPREF=CP1.INF+CP2.INF+CP3.INF
SET GPIREF=GPI1.INF+GPI2.INF+GPI3.INF
SET PMREF=PM1.INF+PM2.INF+PM3.INF+PM4.INF+PM5.INF
SET WPSREF=WPS1.INF+WPS2.INF+WPS3.INF
SET MMREF=MMREF1.INF+MMREF2.INF+MMREF3.INF
SET SMADDSTAR=1
SET SMEMIT=h;ih;c
SET SOMBASE=%ICCDIR%
SET SMTMP=%ICCDIR%\TMP
SET SMCLASSES=WPTYPES.IDL
SET TMP=%TMPDIR%
SET HELPNDX=EPMKWHLP.NDX+tcppr.ndx+CPP.NDX+CPPBRS.NDX+%HELPNDX%
SET CPPLOCAL=%ICCDIR%
SET CPPMAIN=%ICCDIR%
SET CPPWORK=%ICCDIR%
SET IWF.DEFAULT_PRJ=CPPDFTPRJ
REM SET THREADS=512
SET IWF.SOLUTION_LANG_SUPPORT=CPPIBS30;ENG
SET IPF_KEYS=SHOWNAV+%IPF_KEYS%
SET VACPP_SHARED=FALSE
SET IWFHELP=IWFHDI.INF
REM SET IWFOPT=%ICCDIR%

echo.
echo ****************************************************************
echo           Environment variables set up for ICC
echo ****************************************************************

%COMSPEC%

endlocal

echo.
echo ****************************************************************
echo                 Back to original configuration
echo ****************************************************************



